import React,{ useContext, useEffect, useState } from 'react'
import Head from 'next/head'
import NFT from '../components/NFT';
import { Config } from './_app';

function Marketplace() {
    const context = useContext(Config);
    const [nfts, setNfts] = useState([])

    useEffect(() => {
       loadNFTs()
    }, [])

    async function loadNFTs(){
        const data = await context.marketplaceContract.fetchMarketItems();
        setNfts(data) 
    }

    return (
        <div>
            <Head>
                <title>Marketplace - Promise NFT{`'`}s</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 grid-flow-row gap-10 mt-10">
                    {
                        nfts?.map((i,key)=>{
                            return(
                                <div key={key}>
                                    <NFT data={i} market={true}/>
                                </div>
                            )
                        })
                    }   
            </div>
        </div>
    )
}

export default Marketplace
